name: PlotMe-DefaultGenerator
main: com.worldcretornica.plotme.defaultgenerator.BukkitDefaultGenerator
version: 0.17
authors: [ZachBora, MattBDev]
load: STARTUP
loadbefore: [Multiverse-Core, MultiWorld]
depend: [PlotMe]
description: >
             Handles plot creation