name: PlotMe-DefaultGenerator
main: com.worldcretornica.plotme.defaultgenerator.DefaultGenerator
version: 0.16.1
authors: [ZachBora, MattBDev]
load: STARTUP
loadbefore: [Multiverse-Core, MultiWorld]
softdepend: [PlotMe]
description: >
             Handles plot creation
commands:
  plotGenVersion:
    description: Get PlotMeGenerator Version