name: ${project.name}
main: ${main.class}
version: ${project.version}
authors: [ZachBora, MattBDev]
load: startup
loadbefore: [Multiverse-Core, MultiWorld, PlotMe]
description: >
             Handles plot creation
commands:
  plotGenVersion:
    description: Get PlotMeGenerator Version