name: PlotMe-DefaultGenerator
main: com.worldcretornica.plotme.defaultgenerator.DefaultGenerator
version: ${project.version}
authors: [ZachBora, MattBDev]
load: STARTUP
loadbefore: [Multiverse-Core, MultiWorld, PlotMe]
description: >
             Handles plot creation
commands:
  plotGenVersion:
    description: Get PlotMeGenerator Version