name: PlotMe-DefaultGenerator
main: com.worldcretornica.plotme.defaultgenerator.bukkit.BukkitDefaultGeneratorerator
version: 0.17
authors: [ZachBora, MattBDev]
load: STARTUP
loadbefore: [Multiverse-Core, MultiWorld]
softdepend: [PlotMe]
description: >
             Handles plot creation